name: RasPi Pico CoreMark Build

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@main
      with:
        fetch-depth: 0

    - name: Generate Changelog
      uses: BobAnkh/auto-generate-changelog@v1.2.5
      with:
        ACCESS_TOKEN: ${{secrets.GITHUB_TOKEN}}
        COMMIT_MESSAGE: 'CHANGELOG: Update Release notes'
        TYPE: 'feat:Feature,fix:Bug Fixes,docs:Documentation,refactor:Refactor,perf:Performance Improvements'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y cmake gcc-arm-none-eabi libnewlib-arm-none-eabi libstdc++-arm-none-eabi-newlib

    - name: Set up Python
      uses: actions/setup-python@main
      with:
        python-version: '3.x'

    - name: Install RP2040 SDK
      run: |
        git clone https://github.com/raspberrypi/pico-sdk.git
        cd pico-sdk
        git submodule update --init
        echo "PICO_SDK_PATH=$(pwd)" >> $GITHUB_ENV

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -DPICO_PLATFORM=rp2040 -DPICO_SDK_PATH=$PICO_SDK_PATH

    - name: Build firmware
      run: |
        cd build
        echo "Build machine has $(nproc) cores."
        make -j$(nproc)

    - name: Check if release files exists
      run: |
        cd build
        FILE=Coremark-RP2040.uf2

        if [ -f "$FILE" ]; then
            echo "$FILE exists."
        fi

    - name: Create release
      id: create_release
      uses: softprops/action-gh-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        files: |
          build/Coremark-RP2040.elf
          build/Coremark-RP2040.hex
          build/Coremark-RP2040.uf2
